export const STORAGE_KEYS = {
  TEMPLATES: 'archestra_db_templates_v1',
  OBJECTS: 'archestra_db_objects_v1',
  PROPERTIES: 'archestra_db_properties_v1',
  SCRIPTS: 'archestra_db_scripts_v1',
  DEPLOYMENT_FOLDERS: 'archestra_db_deployment_folders_v1',
  DEPLOYMENT_NODES: 'archestra_db_deployment_nodes_v1',
  WIDGETS: 'archestra_db_widgets_v1',
  WIDGET_FOLDERS: 'archestra_db_widget_folders_v1',
  WIDGET_NODES: 'archestra_db_widget_nodes_v1',
  ASSOCIATED_WIDGETS: 'archestra_db_associated_widgets_v1',
  MOCK_CONFIGS: 'archestra_db_mock_configs_v1',
  SIMULATOR_SETTINGS: 'archestra_db_simulator_settings_v1',
  SEEDED: 'archestra_db_is_seeded_v1',
  SCREENS: 'archestra_db_screens_v1',
  SCREEN_FOLDERS: 'archestra_db_screen_folders_v1',
  SCREEN_NODES: 'archestra_db_screen_nodes_v1',
  ALARM_EVENTS: 'archestra_db_alarm_events_v1',
  FLOWCHARTS: 'archestra_db_flowcharts_v1',
  FLOWCHART_FOLDERS: 'archestra_db_flowchart_folders_v1',
  FLOWCHART_NODES: 'archestra_db_flowchart_nodes_v1',
  EVENT_CONFIGS: 'archestra_db_event_configs_v1',
  EVENT_HISTORY: 'archestra_db_event_history_v1',
  OPC_NODES: 'archestra_db_opc_nodes_v1',
  SECURITY_USERS: 'archestra_db_security_users_v1',
  SECURITY_GROUPS: 'archestra_db_security_groups_v1',
  SECURITY_PROFILES: 'archestra_db_security_profiles_v1',
  SECURITY_ROLES: 'archestra_db_security_roles_v1',
  SECURITY_PERMISSION_CONFIGS: 'archestra_db_security_permission_configs_v1',
  SECURITY_AUDIT_LOGS: 'archestra_db_security_audit_logs_v1',
  PRODUCTS: 'archestra_db_products_v1',
  AREAS: 'archestra_db_areas_v1',
  MOVEMENTS: 'archestra_db_movements_v1',
  GRID_SCREENS: 'archestra_db_grid_screens_v1',
  LOGS: 'archestra_db_logs_v1',
} as const;



